### ISSUE TITLE
Impact of Ubuntu 24.04 upgrade

### ISSUE THREAD

**Issue by saumier** [culturecreates/artsdata-pipeline-action#10]
In artsdata-fetch-and-push we are getting the warning:
```
ubuntu-latest pipelines will use ubuntu-24.04 soon. For more details, see https://github.com/actions/runner-images/issues/10636
```

Please check if the Artsdata Pipeline Action will work as expected with ubuntu-24.04.

**Comment by dev-aravind** [comment]
@saumier This should not be an issue as I am running Ubuntu 24.04.1 LTS on my local machine and the pipeline works perfectly during my testing.

**Comment by saumier** [comment]
Thanks.
