### ISSUE TITLE
SPARQL missing test

### ISSUE THREAD

**Issue by saumier** [culturecreates/artsdata-pipeline-action#3]
Please add tests for each sparql.

- fix_country_name sparql is missing tests
- add_derived_from sparql is missing tests

The tests help ensure the sparql is working, and also documents the sparql.  Today I had a question about the SPARQL that fixeds time zones and the tests helped me understand the cases it covers. So the tests are very useful. 

All the tests can be run with the command `rake`

**Comment by dev-aravind** [comment]
@saumier The tests are now added. You can find them [here](https://github.com/culturecreates/artsdata-pipeline-action/tree/main/tests).
